"""Initial migration

Revision ID: b218665b75e2
Revises: 
Create Date: 2025-12-05 16:22:01.609791

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b218665b75e2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('accounts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sa.String(length=36), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=True),
    sa.Column('email_verified', sa.Boolean(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_admin', sa.Boolean(), nullable=True),
    sa.Column('credits_remaining', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('failed_login_attempts', sa.Integer(), nullable=True),
    sa.Column('locked_until', sa.DateTime(), nullable=True),
    sa.Column('last_login_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username'),
    sa.UniqueConstraint('uuid')
    )
    with op.batch_alter_table('accounts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_accounts_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_accounts_email'), ['email'], unique=True)

    op.create_table('packages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('credits', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_featured', sa.Boolean(), nullable=True),
    sa.Column('display_order', sa.Integer(), nullable=True),
    sa.Column('badge', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('packages', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_packages_code'), ['code'], unique=True)
        batch_op.create_index(batch_op.f('ix_packages_display_order'), ['display_order'], unique=False)
        batch_op.create_index(batch_op.f('ix_packages_is_active'), ['is_active'], unique=False)

    op.create_table('account_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('session_token_hash', sa.String(length=255), nullable=False),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('last_active_at', sa.DateTime(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('account_sessions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_account_sessions_account_id'), ['account_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_account_sessions_expires_at'), ['expires_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_account_sessions_session_token_hash'), ['session_token_hash'], unique=False)

    op.create_table('analytics_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=True),
    sa.Column('event_type', sa.String(length=100), nullable=False),
    sa.Column('event_data', sa.JSON(), nullable=True),
    sa.Column('session_id', sa.String(length=100), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('analytics_events', schema=None) as batch_op:
        batch_op.create_index('idx_account_event_type', ['account_id', 'event_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_analytics_events_account_id'), ['account_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_analytics_events_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_analytics_events_event_type'), ['event_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_analytics_events_session_id'), ['session_id'], unique=False)

    op.create_table('api_keys',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('key_hash', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('rate_limit', sa.Integer(), nullable=True),
    sa.Column('rate_limit_period', sa.String(length=20), nullable=True),
    sa.Column('scopes', sa.JSON(), nullable=True),
    sa.Column('allowed_ips', sa.Text(), nullable=True),
    sa.Column('last_used_at', sa.DateTime(), nullable=True),
    sa.Column('usage_count', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('api_keys', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_api_keys_account_id'), ['account_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_api_keys_is_active'), ['is_active'], unique=False)
        batch_op.create_index(batch_op.f('ix_api_keys_key_hash'), ['key_hash'], unique=False)

    op.create_table('conversions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sa.String(length=36), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('original_image_url', sa.String(length=500), nullable=False),
    sa.Column('original_filename', sa.String(length=255), nullable=False),
    sa.Column('framework', sa.String(length=50), nullable=False),
    sa.Column('css_framework', sa.String(length=50), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('retry_count', sa.Integer(), nullable=True),
    sa.Column('generated_html', sa.Text(), nullable=True),
    sa.Column('generated_css', sa.Text(), nullable=True),
    sa.Column('generated_js', sa.Text(), nullable=True),
    sa.Column('preview_url', sa.String(length=500), nullable=True),
    sa.Column('download_url', sa.String(length=500), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('processing_time', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('tokens_used', sa.Integer(), nullable=True),
    sa.Column('cost', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('conversions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_conversions_account_id'), ['account_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_conversions_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_conversions_framework'), ['framework'], unique=False)
        batch_op.create_index(batch_op.f('ix_conversions_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_conversions_uuid'), ['uuid'], unique=True)

    op.create_table('email_verification_tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('token_hash', sa.String(length=255), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('verified', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('email_verification_tokens', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_email_verification_tokens_account_id'), ['account_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_email_verification_tokens_expires_at'), ['expires_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_email_verification_tokens_token_hash'), ['token_hash'], unique=False)

    op.create_table('orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=True),
    sa.Column('tax_amount', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('discount_amount', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('coupon_code', sa.String(length=50), nullable=True),
    sa.Column('package_type', sa.String(length=50), nullable=False),
    sa.Column('credits_purchased', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('stripe_payment_id', sa.String(length=255), nullable=True),
    sa.Column('stripe_session_id', sa.String(length=255), nullable=True),
    sa.Column('payment_method_type', sa.String(length=50), nullable=True),
    sa.Column('extra_data', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_orders_account_id'), ['account_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_orders_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_orders_package_type'), ['package_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_orders_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_orders_stripe_payment_id'), ['stripe_payment_id'], unique=True)

    op.create_table('password_reset_tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('token_hash', sa.String(length=255), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('used', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('password_reset_tokens', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_password_reset_tokens_account_id'), ['account_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_password_reset_tokens_expires_at'), ['expires_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_password_reset_tokens_token_hash'), ['token_hash'], unique=False)

    op.create_table('conversion_feedback',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('conversion_id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('feedback_text', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.ForeignKeyConstraint(['conversion_id'], ['conversions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('conversion_id', 'account_id', name='unique_conversion_feedback')
    )
    with op.batch_alter_table('conversion_feedback', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_conversion_feedback_account_id'), ['account_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_conversion_feedback_conversion_id'), ['conversion_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_conversion_feedback_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_conversion_feedback_rating'), ['rating'], unique=False)

    op.create_table('credits_transactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=True),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('balance_after', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('transaction_type', sa.String(length=20), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('extra_data', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('credits_transactions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_credits_transactions_account_id'), ['account_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_credits_transactions_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_credits_transactions_transaction_type'), ['transaction_type'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('credits_transactions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_credits_transactions_transaction_type'))
        batch_op.drop_index(batch_op.f('ix_credits_transactions_created_at'))
        batch_op.drop_index(batch_op.f('ix_credits_transactions_account_id'))

    op.drop_table('credits_transactions')
    with op.batch_alter_table('conversion_feedback', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_conversion_feedback_rating'))
        batch_op.drop_index(batch_op.f('ix_conversion_feedback_created_at'))
        batch_op.drop_index(batch_op.f('ix_conversion_feedback_conversion_id'))
        batch_op.drop_index(batch_op.f('ix_conversion_feedback_account_id'))

    op.drop_table('conversion_feedback')
    with op.batch_alter_table('password_reset_tokens', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_password_reset_tokens_token_hash'))
        batch_op.drop_index(batch_op.f('ix_password_reset_tokens_expires_at'))
        batch_op.drop_index(batch_op.f('ix_password_reset_tokens_account_id'))

    op.drop_table('password_reset_tokens')
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_orders_stripe_payment_id'))
        batch_op.drop_index(batch_op.f('ix_orders_status'))
        batch_op.drop_index(batch_op.f('ix_orders_package_type'))
        batch_op.drop_index(batch_op.f('ix_orders_created_at'))
        batch_op.drop_index(batch_op.f('ix_orders_account_id'))

    op.drop_table('orders')
    with op.batch_alter_table('email_verification_tokens', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_email_verification_tokens_token_hash'))
        batch_op.drop_index(batch_op.f('ix_email_verification_tokens_expires_at'))
        batch_op.drop_index(batch_op.f('ix_email_verification_tokens_account_id'))

    op.drop_table('email_verification_tokens')
    with op.batch_alter_table('conversions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_conversions_uuid'))
        batch_op.drop_index(batch_op.f('ix_conversions_status'))
        batch_op.drop_index(batch_op.f('ix_conversions_framework'))
        batch_op.drop_index(batch_op.f('ix_conversions_created_at'))
        batch_op.drop_index(batch_op.f('ix_conversions_account_id'))

    op.drop_table('conversions')
    with op.batch_alter_table('api_keys', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_api_keys_key_hash'))
        batch_op.drop_index(batch_op.f('ix_api_keys_is_active'))
        batch_op.drop_index(batch_op.f('ix_api_keys_account_id'))

    op.drop_table('api_keys')
    with op.batch_alter_table('analytics_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_analytics_events_session_id'))
        batch_op.drop_index(batch_op.f('ix_analytics_events_event_type'))
        batch_op.drop_index(batch_op.f('ix_analytics_events_created_at'))
        batch_op.drop_index(batch_op.f('ix_analytics_events_account_id'))
        batch_op.drop_index('idx_account_event_type')

    op.drop_table('analytics_events')
    with op.batch_alter_table('account_sessions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_account_sessions_session_token_hash'))
        batch_op.drop_index(batch_op.f('ix_account_sessions_expires_at'))
        batch_op.drop_index(batch_op.f('ix_account_sessions_account_id'))

    op.drop_table('account_sessions')
    with op.batch_alter_table('packages', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_packages_is_active'))
        batch_op.drop_index(batch_op.f('ix_packages_display_order'))
        batch_op.drop_index(batch_op.f('ix_packages_code'))

    op.drop_table('packages')
    with op.batch_alter_table('accounts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_accounts_email'))
        batch_op.drop_index(batch_op.f('ix_accounts_created_at'))

    op.drop_table('accounts')
    # ### end Alembic commands ###
